import { Metadata } from "next";
import Image from "next/image";
import styles from "./page.module.css";
import { Button, Htag } from "./components";
import Logo from "../public/vercel.svg";

// export const metadata: Metadata = {
//   title: 'First page',
//   description: 'Generated by create next app',

// }

// export async function generateMetadata(): Promise<Metadata> {
//   return {
//     title: 'First page',
//     description: 'Generated by create next app',
//   }
// }

export default function Home() {
  return (
    <>
      <Logo />
      <Htag tag="h1">Текст</Htag>
      <Button appearance="primary" arrow="right">
        Click
      </Button>
      <Button appearance="ghost" arrow="right">
        Click
      </Button>
    </>
  );
}
