import { Metadata } from "next";
import Image from "next/image";
import styles from "./page.module.css";

// export const metadata: Metadata = {
//   title: 'First page',
//   description: 'Generated by create next app',

// }

// export async function generateMetadata(): Promise<Metadata> {
//   return {
//     title: 'First page',
//     description: 'Generated by create next app',
//   }
// }

export default function Home() {
  return <div>Hello World</div>;
}
